name = "SossGen"
uuid = "49da98a9-8e90-4571-9d91-650d79966921"
authors = ["Chad Scherrer"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
